[versions]
minSdk = "28"
targetSdk = "36"
compileSdk = "36"

jdk = "21"

aboutlibraries = "14.0.0-b02"
activity-compose = "1.12.2"
agp = "9.0.0"
androidxTestRules = "1.7.0"
browser = "1.9.0"
compose-bom = "2026.01.00"
hilt = "2.59"
hilt-lifecycle-viewmodel-compose = "1.3.0"
junit = "4.13.2"
kotlin = "2.3.0"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
ksp = "2.3.5"
lifecycle = "2.10.0"
markdown = "0.7.3"
napier = "2.7.1"
navigation2 = "2.9.6"
navigation3 = "1.0.0"
preview-scanner = "0.8.1"
robolectric = "4.16.1"
roborazzi = "1.57.0"
turbine = "1.2.1"

[libraries]
aboutlibraries-ui = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-lifecycle-viewmodel-compose = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel-compose", version.ref = "hilt-lifecycle-viewmodel-compose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
lifecycle-viewmodel-navigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
markdown = { group = "org.jetbrains", name = "markdown", version.ref = "markdown" }
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }
navigation2 = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation2" }
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
preview-scanner = { group = "io.github.sergio-sastre.ComposablePreviewScanner", name = "android", version.ref = "preview-scanner" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose-preview-scanner-support = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose-preview-scanner-support", version.ref = "roborazzi" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
roborazzi-gradlePlugin = { group = "io.github.takahirom.roborazzi", name = "roborazzi-gradle-plugin", version.ref = "roborazzi" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

buildlogic-android-application = { id = "buildlogic.android.application", version = "unspecified" }
buildlogic-android-library = { id = "buildlogic.android.library", version = "unspecified" }
buildlogic-compose = { id = "buildlogic.compose", version = "unspecified" }
buildlogic-hilt = { id = "buildlogic.hilt", version = "unspecified" }
buildlogic-robolectric = { id = "buildlogic.robolectric", version = "unspecified" }
buildlogic-roborazzi = { id = "buildlogic.roborazzi", version = "unspecified" }
